name: food_delivery
description: A Flutter Food Delivery Application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
#  sdk: '>=2.12.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  gradient_widgets: ^0.5.1
  geolocator: ^7.0.3
  provider: ^5.0.0
  intl: ^0.17.0
  lottie: ^1.0.0
  introduction_screen: ^2.1.0



  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - images/

